Begin type annotation
RickCarlino/farmbot-web-frontend pull request #4
Opened 2016-09-16 21:51 UTC by ConnorRigby

We should probably remember to change noImplecitAny to false at some point.

2016-09-16 21:54 UTC, RickCarlino commented on src/config/actions.tsx
> +  return (dispatch: Function, getState: Function) => {
This is a `Thunk`.

2016-09-16 21:55 UTC, RickCarlino commented on src/config/reducer.tsx
> +  port: (location.host as any)["includes"] ("localhost") ? "3000" : (location.port || "80")
This is actually a `string`.

2016-09-16 21:56 UTC, RickCarlino commented on src/controls/controls.tsx
> +    let num = (this.props.bot.hardware as any)[this.props.axis];
Could this be a `Map<string>` or `{[name: string]: string}`?

2016-09-16 21:56 UTC, RickCarlino commented on src/controls/controls.tsx
> +    let num = (this.props.bot.hardware as any)[this.props.axis];
Not sure 100%, actually.

2016-09-16 21:57 UTC, RickCarlino commented on src/controls/direction_button.tsx
> +    (payload as any)[this.props.axis] = (this.props.steps || 250 ) * multiplier;
Could be `number`, right?

2016-09-16 21:57 UTC, RickCarlino commented on src/controls/toggle_button.tsx
> +      return (captions as any) [togval];
Probably `as string`.

2016-09-16 21:58 UTC, RickCarlino commented on src/controls/toggle_button.tsx
> +    return (cssClasses as any)[String(this.props.toggleval)] || yellowCSS;
Same as above. `as string`.

2016-09-16 21:59 UTC, RickCarlino commented on src/generate_reducer.ts
> +const NOOP = (s: any, a: ReduxAction<{}>) => s;
I think this one is `(s: T, . . . . )`

2016-09-16 22:00 UTC, RickCarlino commented on src/generate_reducer.ts
> +const NOOP = (s: any, a: ReduxAction<{}>) => s;
Actually, move `NOOP` into the function definition after the current first line.

2016-09-16 22:01 UTC, RickCarlino commented on src/sequences/actions.ts
> +  return function(dispatch: Function, getState: Function){
This is a `Thunk`

2016-09-16 22:02 UTC, RickCarlino commented on tsconfig.json
> +    "noImplicitAny": true,
Once you implement all the suggestions, you can flip this back to normal.

2016-09-16 22:03 UTC, RickCarlino requested changes
Cool. Just a few things.

2016-09-17 16:44 UTC, RickCarlino commented on src/devices/interfaces.ts
> +}
TODO: Delete this.

2016-09-17 16:47 UTC, ConnorRigby commented on src/devices/message_catcher.ts
> +  let matchCount = (results.invert(true).value() as any)["true"] || [];
let matchCount = (results.invert(true).value() as {[name: string}: any)["true"] || [];

2016-09-17 16:48 UTC, RickCarlino commented on src/devices/reducer.tsx
> +    let axisBuffer: any = _.assign({}, state.axisBuffer);
This is defensive copying. No longer needs to be done.

2016-09-17 16:48 UTC, RickCarlino commented on src/devices/reducer.tsx
> +    let settingsBuffer: any = _.assign({}, state.settingsBuffer);
Same thing. Looks like more defensive copying.

2016-09-17 16:51 UTC, RickCarlino commented on src/regimens/bulk_scheduler/reducer.ts
> +    return newState(state.currentRegimen);
Is this just defensive copying? It might not be, but please check to make sure.

2016-09-17 16:51 UTC, RickCarlino reviewed
:clap: Looks good. See my comment and then let's merge this thang.

2016-09-17 17:00 UTC, RickCarlino commented on src/config/reducer.tsx
> +  port: (location.host as any)["includes"] ("localhost") ? "3000" : (location.port || "80")
Not relevant. Nvm

2016-09-17 17:01 UTC, merged